name: MServerUI
version: 1.7.0
description: information plugin made simple
author: RimVG
api:
- 5.0.0
main: RimVG\PluginDev\Main
commands:
  ms:
    description: MServerUI plugin command GUI created by [ RimVG ]
    permission: ms.ui
permissions:
  ms.ui:
    description: Allow player use cmd
    default: true
